import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Obsidian vault living inside the repo -- not source, and its bundled
    // plugins emit thousands of warnings that drown out real findings.
    ".obsidian/**",
  ]),
  {
    // Treat a leading underscore as "intentionally unused" for vars, args, caught errors,
    // and destructured-array holes -- the conventional escape hatch when a binding can't be omitted.
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // Vendored shadcn/diceui code -- copy-in, regenerated by the CLI, so not hand-fixed.
    // compose-refs.ts is a diceui `lib` registry file; it lands in src/lib per components.json.
    files: ["src/components/ui/**", "src/lib/compose-refs.ts"],
    rules: {
      "react-hooks/preserve-manual-memoization": "off",
      "react-hooks/refs": "off",
      "react-hooks/use-memo": "off",
      "react-hooks/exhaustive-deps": "off",
      "react-hooks/set-state-in-effect": "off",
      "jsx-a11y/role-supports-aria-props": "off",
    },
  },
]);

export default eslintConfig;
